### ISSUE TITLE
BuySell does not work with xlm/euro in the feed from kraken via the config file

### ISSUE THREAD

**Issue by brianopedal** [lightyeario/kelp#13]
## buysell config file
When changing the buysell configuration file. to read krakens xlm/usd orders to  xlm/euro
The bot does not understand the  xlm euro pair, and throws an error.

I think the correct behavior in this situation is for the bot to ...

## Steps To Reproduce
Open config file and change what is read from kraken from xxlm/zusd to xxlm/zeur
https://support.kraken.com/hc/en-us/articles/360001185506-Asset-Codes

**Comment by nikhilsaraf** [comment]
@brianopedal can you share the DATA_FEED_URL string that you are trying to use?

**Comment by brianopedal** [comment]
buysell.cfg file
line 17:

DATA_FEED_A_URL="kraken/XXLM/ZEUR"

**Comment by nikhilsaraf** [comment]
@brianopedal that's a great find. The EUR currency isn't recognized by the current version of the bot (v1.0.0-rc2).

I'm just adding a fix for this and uploading a new release candidate for this.
