### ISSUE TITLE
Question Regarding Kelp in case the bot receives funds

### ISSUE THREAD

**Issue by PedityOfficial** [lightyeario/kelp#24]
We are currently testing kelp with small amount of funds in the live market for our project.  This is an amazing tool and thank you interstellar team for creating this. It is working great with small amount of funds and we are planning to increase it but I have a question before we do that.
Our purpose is to create liquidity for the token. 

**Question**
Suppose we are using kelp with balanced config and fund the bot with equal value of both asset. The bots start working and based on config parameters, it will create buy/sell offers. Suppose someone sends more funds of either asset, now in that the value of both asset will not be equal in that bot account. It might hamper the functionality of the bot and an attacker can use this to manipulate the price.
Is there any funntion in Kelp bot that if unwanted funds(of either of the assets) are sent to bot account, it will not hamper the functionality of Kelp ?

**Comment by nikhilsaraf** [comment]
@PedityOfficial thank you for using Kelp, we're glad that you like the tool.

can you please post your question on our Q&A forum: https://stellar.stackexchange.com using the `kelp` tag. Feel free to post a link to that question here and I can answer it on there and close out this issue.

**Comment by nikhilsaraf** [comment]
@PedityOfficial  I posted and answered your question, see here: https://stellar.stackexchange.com/questions/1846/how-does-kelps-balanced-strategy-react-to-the-account-receiving-funds
