### ISSUE TITLE
Manual setting of initial price for balanced strat

### ISSUE THREAD

**Issue by Reidmcc** [lightyeario/kelp#35]
## Desired Behavior
The bot would be able to know what initial center price to set by another method than balance calculation.

## Impact
This would allow users to set up the balanced strategy without minute fiddling with account balances. It could also help address the concern from https://github.com/lightyeario/kelp/issues/24.

## Feature Suggestion
Add the ability for the user to manually set the initial middle price.

## Additional context
Another option would be to have the bot read the current SDEX offers and set the center price between the top buy and bottom sell. Doing it that way would only allow the user to consider the extant price fair or use the bot's current balance-based mode; a manual price setting is more flexible.

## Specification
1. Add a parameter to the `balanced` config file where the user would enter their starting middle price
2. Alter the calculation code to allow import of the config price value (for first run of the bot session only)
3. Add a command line flag to activate this behavior

I'll try coding this out but may not be able to figure out the calculation modification without breaking the existing method.

**Comment by Reidmcc** [comment]
After more detailed examination of the balancedLevelProvider code I think this is probably better accomplished as a new strategy. Since the balanced levels are calculated off held assets every time, a fixed start price wouldn't be considered at all after the first run. So this is more like a modification to the buysell strategy that would track SDEX prices instead of outside prices.

**Comment by nikhilsaraf** [comment]
I can see Kelp having a new command that updates an account's balances for two assets to set it to a price taken from a price feed (can be an SDEX market as input too). Although I think this is also overkill compared to just setting your initial balance correctly.

**Comment by Reidmcc** [comment]
@nikhilsaraf I agree. I'll think about doing something pegged to extant SDEX price as a separate strategy.
