### ISSUE TITLE
Submitting no levels on sell side prevents buy side from updating

### ISSUE THREAD

**Issue by Reidmcc** [lightyeario/kelp#41]
## Describe the bug
If the bot's strategy logic results in no levels being generated for the sell side, buy levels are not checked for refresh. This does not happen in the opposite direction; if there are no buy levels, sell levels are still checked. No error is thrown.

## Expected behavior
The bot should evaluate existing levels and generate new levels as normal regardless of whether the bot is placing orders on the other side.

## Frequency
Always if the conditions are met.

## Steps To Reproduce

1. Set up a strategy that sometimes validly creates no levels on one side of the orderbook. I'm using my strategy submitted in PR https://github.com/lightyeario/kelp/pull/39. In this case the `MAINTAIN_BALANCE_PERCENT` parameter instructs the strategy to place no orders on one side when that side's balance is below a certain threshold. 
2. Set the parameter such that it places no sell orders, e.g. `MAINTAIN_BALANCE_PERCENT` higher than the sold asset balance ratio but lower than the buy asset's ratio.
3. Set `PRICE_TOLERANCE` low so the bot should update orders frequently.
4. Run the bot. It will successfully place buy orders on the first cycle, presumably because it is expecting no existing levels.
5. Wait for the price to change towards the sell side enough to trigger `PRICE_TOLERANCE`.
6. The buy orders will sit as they are regardless of increase in price.

## Possible Solution
I think this can be fixed by removing the `break` on line 130 of sellSideStrategy. This part:
```
if hitCapacityLimit {
			if isModify {
				delOp := s.sdex.DeleteOffer(offers[i])
				log.Printf("deleting offer because we previously hit the capacity limit, offerId=%d\n", offers[i].ID)
				deleteOps = append(deleteOps, delOp)
				continue
			} else {
				// we can break because we would never see a modify operation happen after a non-modify operation
				break
			}
		}
```
Using a strategy with valid asymmetrical orders I think you can see a modify operation after a non-modify operation. In this case, I think the buy-side levels aren't being checked because the loop is breaking before it gets to them. Which would line up with this being a one-sided problem; if the sell levels are checked first then a break triggered by no buy levels would be after the sell levels are already done.

I'm now trying a version with the `break` replaced with another `continue` to see if the problem occurs in that case; I'll update if I have clear evidence either way.

## Your Environment
  version: v1.1.1-9-g59a9340e-dirty
  git hash: 59a9340e7a16716ee650e61ae2615ddab9f97787-dirty
  build date: 20181030T233844Z
  GOOS: linux
  GOARCH: amd64

## Context
I am unable to run strategies with asymmetrical logic. This could also possibly affect things like a maker-only mode where some levels could be validly skipped.

**Comment by Reidmcc** [comment]
@nikhilsaraf I ran it locally with the change and the issue still occurred, so the `break` doesn't seem to be the problem. After that I altered my strategy to always place orders on both sides, but with very small amounts below the balance maintenance level; that modified strategy did not show any similar side-related problems. It's possible that this was an issue with my level generation code, but if that logic failed (without generating an error) it would have returned a blank level set just as if it intentionally did so.

A couple questions about how the bot processes levels:

1. When the bot processes the buy and sell levels are those done separately for sell and buy? That is, are the two kinds of levels present in the same loop at all and potentially affected by a `break` in the single loop? After more examination it looks like they are not in the same loop; rather sell and buy have entirely separate sellSideStrategy objects. In which case my thought as to the cause is definitely not the case.

2. What behavior would you expect from the bot if it is passed a blank level set and thus has nothing to compare with existing orders? 

3. Is there a circumstance where not breaking would be a problem? If the `break`'s whole purpose it to avoid wasted processing time, I'd suggest removing it to avoid it causing problems with unexpected user-coded strategies.

The core requirement is that strategies should be able to _sometimes_ return instructions to place no orders without that causing problems with subsequent comparison cycles (on either side).

So the bot needs to be able to process inconsistent instructions like:

First cycle place orders -> Next cycle follow instructions to place no orders (and thus delete the old orders) -> Next cycle place orders again

**Comment by nikhilsaraf** [comment]
@Reidmcc answers to your questions:

1. Yes, they are done separately. i.e. they are not in the same loop, so a break would only affect one side.

2. if the level provider returns a blank level set then the sellSideStrategy logic will delete all the offers on both sides. Note that the levelProvider is returning orders for both sides -- you can always inject a different level provider into the buy side compared to the sell side.

3. based on how the sellSideStrategy converts levels to orders, by definition there will be no work left after the point we break, regardless of the strategy used. That's the abstraction provided by the levelProvider. If you are looking for something more complex then that should be it's own strategy, although I think that most (if not all) strategies can be modeled under the levelProvider abstraction :)

Yes, the level provider can achieve this -- if in the first iteration it returns 0 levels and on a subsequent level it returns 3 levels then the bot will delete all offers in the first iteration and create 3 new offers on the second iteration. If you want the bot to not place any new orders then the level provider should return the existing levels as it's output.

You can think of the level provider as an object that outputs a state and the sellSideStrategy as the object that takes the account's offers from the existing state to the state defined by the level provider.

**Comment by Reidmcc** [comment]
Ok, that confirms the understanding I eventually came to. I'm closing this issue since there is no evident bug.
