### ISSUE TITLE
don't use ALL_CAPS in Go struct definitions for configs

### ISSUE THREAD

**Issue by nikhilsaraf** [lightyeario/kelp#6]
## Describe the bug
The bot should follow go convention when naming config variables in `.go` files.

## Expected behavior
Config variables should be changed to use camelCase formatted names; the config files should remain the same in ALL_CAPS format.

## Frequency
The frequency is: Always

## Steps To Reproduce
N/A

## Possible Solution
This bug can be fixed by using double-quoted formatting near config structs.

## Your Environment
    version: v1.0.0-rc1
    git hash: 337f478b0e7a1dc235aef31788754bc1ab11b6a1
    build date: 20180813T231816Z
    GOOS: linux
    GOARCH: amd64

## Context
I am unable to look at errors in the code with the noise from these formatting errors because of this bug.

## Attachments
No relevant attachments.

**Comment by Reidmcc** [comment]
I'm planning to work on this; can you clarify how the double-quoted formatting ties into the case change?

**Comment by nikhilsaraf** [comment]
@Reidmcc thanks for taking this on. Assigning this issue to you.

You would need to use the `toml` tag with the ALL_CAPS version of the field name, like so:
```
tradingSecretSeed     string `toml:"TRADING_SECRET_SEED"`
```
(see the [examples section of the BurntSushi/toml parser](https://github.com/BurntSushi/toml#examples))

You can keep the existing `valid` tag for now and add the second `toml` tag using a space to separate them. Here's an [example](https://stackoverflow.com/a/18635910/1484710)

**Comment by Reidmcc** [comment]
This doesn't seem to work; the executable builds but throws a _Unknown fields_ error when attempting to parse the strategy config. If you leave one of the fields as ALL_CAPS that fields parses but the changed fields do not. For example, if the struct is:

```
type balancedConfig struct {
	PRICE_TOLERANCE               float64 `valid:"-" toml:"PRICE_TOLERANCE"`
	amountTolerance               float64 `valid:"-" toml:"AMOUNT_TOLERANCE"`
	spread                        float64 `valid:"-" toml:"SPREAD"`                       
	minAmountSpread               float64 `valid:"-" toml:"MIN_AMOUNT_SPREAD"`            
	maxAmountSpread               float64 `valid:"-" toml:"MAX_AMOUNT_SPREAD"`        
	maxLevels                     int16   `valid:"-" toml:"MAX_LEVELS"`                    
	levelDensity                  float64 `valid:"-" toml:"LEVEL_DENSITY"`                   
	ensureFirstNLevels            int16   `valid:"-" toml:"ENSURE_FIRST_N_LEVELS"`           
	minAmountCarryoverSpread      float64 `valid:"-" toml:"MIN_AMOUNT_CARRYOVER_SPREAD"`     
	maxAmountCarryoverSpread      float64 `valid:"-" toml:"MAX_AMOUNT_CARRYOVER_SPREAD"`     
	carryoverInclusionProbability float64 `valid:"-" toml:"CARRYOVER_INCLUSION_PROBABILITY"`
	virtualBalanceBase            float64 `valid:"-" toml:"VIRTUAL_BALANCE_BASE"`           
	virtualBalanceQuote           float64 `valid:"-" toml:"VIRTUAL_BALANCE_QUOTE"`
}
```

The error comes back with everything except _PRICE_TOLERANCE_ as unknown:

![parse_err](https://user-images.githubusercontent.com/43561569/47250965-35eb6b00-d3f1-11e8-891c-d1cd61b7e9e3.jpg)

Am I missing something?

**Comment by Reidmcc** [comment]
I didn't see the full text of this message separately from the PR message. I'll finish the rest of this soon.
