### ISSUE TITLE
Log output should show current strategy being run

### ISSUE THREAD

**Issue by nikhilsaraf** [lightyeario/kelp#8]
## Desired Behavior
I want to be able to see the selected **strategy** in the log output of the bot

## Impact
The desired behavior will allow me to better analyze logs in retrospect

## Feature Suggestion
We can achieve the desired behavior by printing out this value before the printed configs

**Comment by Reidmcc** [comment]
I've coded this up. Pull request and contributor agreement incoming.

**Comment by nikhilsaraf** [comment]
addressed by https://github.com/lightyeario/kelp/pull/15 (f19c610f53432b2dba25a14db93ccbffa1afa38e)
